name: TrendPilot - Trend Finder Algorithm [ Cron Job ]

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours.
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have dependencies

    - name: Run Script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python proxy_server_git.py  # Replace with your script's name

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Update logs from GitHub Actions run"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
